"""remove english from analysis table comments

Revision ID: 05f659afad17
Revises: 0ec9fa574d93
Create Date: 2026-01-03 17:19:45.060102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05f659afad17'
down_revision: Union[str, None] = '0ec9fa574d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'analysis_dashboards',
        '数据仪表盘管理表',
        existing_comment='BI仪表盘管理表',
        schema=None
    )
    op.alter_column('analysis_datasets', 'table_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='引擎表名',
               existing_comment='DuckDB表名',
               existing_nullable=False)
    op.create_table_comment(
        'analysis_models',
        '数据流程模型表',
        existing_comment='ETL数据模型表',
        schema=None
    )
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_comment='报告全文',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_comment='报告全文',
               existing_nullable=True)
    op.create_table_comment(
        'analysis_models',
        'ETL数据模型表',
        existing_comment='数据流程模型表',
        schema=None
    )
    op.alter_column('analysis_datasets', 'table_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='DuckDB表名',
               existing_comment='引擎表名',
               existing_nullable=False)
    op.create_table_comment(
        'analysis_dashboards',
        'BI仪表盘管理表',
        existing_comment='数据仪表盘管理表',
        schema=None
    )
    # ### end Alembic commands ###







