"""add video module tables

Revision ID: 0b78536eb0ca
Revises: 5da3e4b569bc
Create Date: 2026-01-03 16:19:34.437938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b78536eb0ca'
down_revision: Union[str, None] = '5da3e4b569bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='视频集名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频集描述'),
    sa.Column('cover_video_id', sa.Integer(), nullable=True, comment='封面视频ID'),
    sa.Column('video_count', sa.Integer(), nullable=True, comment='视频数量'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_collections_user_id'), 'video_collections', ['user_id'], unique=False)
    op.create_table('video_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('collection_id', sa.Integer(), nullable=False, comment='所属视频集ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='存储路径'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True, comment='缩略图路径'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='视频标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频描述'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='时长(秒)'),
    sa.Column('width', sa.Integer(), nullable=True, comment='视频宽度'),
    sa.Column('height', sa.Integer(), nullable=True, comment='视频高度'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=50), nullable=True, comment='MIME类型'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['collection_id'], ['video_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_videos_collection_id'), 'video_videos', ['collection_id'], unique=False)
    op.create_index(op.f('ix_video_videos_user_id'), 'video_videos', ['user_id'], unique=False)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_video_videos_user_id'), table_name='video_videos')
    op.drop_index(op.f('ix_video_videos_collection_id'), table_name='video_videos')
    op.drop_table('video_videos')
    op.drop_index(op.f('ix_video_collections_user_id'), table_name='video_collections')
    op.drop_table('video_collections')
    # ### end Alembic commands ###







