"""add ai chat sessions and messages tables

Revision ID: 1892b3228cf8
Revises: 05f659afad17
Create Date: 2026-01-03 19:14:41.029907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1892b3228cf8'
down_revision: Union[str, None] = '05f659afad17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='提供者: local/online'),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True, comment='知识库ID'),
    sa.Column('use_analysis', sa.Boolean(), nullable=False, comment='是否使用数据分析'),
    sa.Column('config', sa.JSON(), nullable=True, comment='会话配置'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='AI对话会话表'
    )
    op.create_index('idx_ai_session_user_updated', 'ai_chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('is_error', sa.Boolean(), nullable=False, comment='是否为错误消息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI对话消息表'
    )
    op.create_index('idx_ai_msg_session_created', 'ai_chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_comment='报告全文',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_comment='报告全文',
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_index('idx_ai_msg_session_created', table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index('idx_ai_session_user_updated', table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    # ### end Alembic commands ###







