"""initial_schema_production

Revision ID: 215f47284b32
Revises: 
Create Date: 2026-01-18 00:11:11.766258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215f47284b32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_albums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='相册名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='相册描述'),
    sa.Column('cover_photo_id', sa.Integer(), nullable=True, comment='封面照片ID'),
    sa.Column('photo_count', sa.Integer(), nullable=True, comment='照片数量'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='相册表'
    )
    op.create_index(op.f('ix_album_albums_user_id'), 'album_albums', ['user_id'], unique=False)
    op.create_table('analysis_charts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='图表名称'),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='关联数据集ID'),
    sa.Column('chart_type', sa.String(length=50), nullable=False, comment='图表类型'),
    sa.Column('config', sa.JSON(), nullable=False, comment='图表配置'),
    sa.Column('description', sa.Text(), nullable=True, comment='图表描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='分析图表保存表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analysis_dashboards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='仪表盘名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='仪表盘描述'),
    sa.Column('widgets', sa.JSON(), nullable=True, comment='组件配置'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据仪表盘管理表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analysis_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='数据集名称'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='来源类型'),
    sa.Column('table_name', sa.String(length=100), nullable=False, comment='引擎表名'),
    sa.Column('config', sa.JSON(), nullable=True, comment='导入配置'),
    sa.Column('row_count', sa.Integer(), nullable=False, comment='数据行数'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据分析集管理表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analysis_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模型名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('graph_config', sa.JSON(), nullable=True, comment='流程图配置'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据流程模型表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analysis_smart_table_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('table_id', sa.Integer(), nullable=False, comment='智能表格ID'),
    sa.Column('row_data', sa.JSON(), nullable=False, comment='行数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能表格数据表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analysis_smart_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='表格名称'),
    sa.Column('fields', sa.JSON(), nullable=False, comment='字段定义'),
    sa.Column('config', sa.JSON(), nullable=True, comment='表格配置'),
    sa.Column('dataset_id', sa.Integer(), nullable=True, comment='关联数据集ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能表格定义表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=50), nullable=False, comment='别名/路径'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='博客分类表'
    )
    op.create_index(op.f('ix_blog_categories_slug'), 'blog_categories', ['slug'], unique=True)
    op.create_table('blog_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='标签名称'),
    sa.Column('slug', sa.String(length=30), nullable=False, comment='标签别名'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='博客标签表'
    )
    op.create_index(op.f('ix_blog_tags_slug'), 'blog_tags', ['slug'], unique=True)
    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='试卷标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='试卷描述'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='总分'),
    sa.Column('pass_score', sa.Float(), nullable=True, comment='及格分数'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='考试时长(分钟)'),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True, comment='题目乱序'),
    sa.Column('shuffle_options', sa.Boolean(), nullable=True, comment='选项乱序'),
    sa.Column('show_answer', sa.Boolean(), nullable=True, comment='交卷后显示答案'),
    sa.Column('allow_review', sa.Boolean(), nullable=True, comment='允许查看解析'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='考试开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='考试结束时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='试卷状态'),
    sa.Column('question_count', sa.Integer(), nullable=True, comment='题目数量'),
    sa.Column('take_count', sa.Integer(), nullable=True, comment='参考人数'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='试卷表'
    )
    op.create_index(op.f('ix_exam_papers_user_id'), 'exam_papers', ['user_id'], unique=False)
    op.create_table('exam_question_banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='题库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='题库描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('question_count', sa.Integer(), nullable=True, comment='题目数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='题库分类表'
    )
    op.create_index(op.f('ix_exam_question_banks_user_id'), 'exam_question_banks', ['user_id'], unique=False)
    op.create_table('lens_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('icon', sa.String(length=10), nullable=False, comment='图标'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='颜色'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据视图分类表'
    )
    op.create_index('ix_lens_categories_order', 'lens_categories', ['order'], unique=False)
    op.create_table('lens_datasources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='数据源名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='数据源类型'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('connection_config', sa.Text(), nullable=True, comment='数据库连接配置'),
    sa.Column('file_config', sa.Text(), nullable=True, comment='文件配置'),
    sa.Column('api_config', sa.Text(), nullable=True, comment='API接口配置'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True, comment='最后连接时间'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='最后错误信息'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='外部数据源配置表'
    )
    op.create_index('ix_lens_datasources_name', 'lens_datasources', ['name'], unique=False)
    op.create_table('lens_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('view_id', sa.Integer(), nullable=False, comment='视图ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据视图收藏表'
    )
    op.create_index('ix_lens_favorites_user', 'lens_favorites', ['user_id'], unique=False)
    op.create_index('ix_lens_favorites_view', 'lens_favorites', ['view_id'], unique=False)
    op.create_table('lens_recent_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('view_id', sa.Integer(), nullable=False, comment='视图ID'),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False, comment='访问时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='最近访问记录表'
    )
    op.create_index('ix_lens_recent_time', 'lens_recent_views', ['accessed_at'], unique=False)
    op.create_index('ix_lens_recent_user', 'lens_recent_views', ['user_id'], unique=False)
    op.create_table('lens_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='视图名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('icon', sa.String(length=10), nullable=False, comment='图标'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类ID'),
    sa.Column('datasource_id', sa.Integer(), nullable=True, comment='关联数据源ID'),
    sa.Column('query_type', sa.String(length=20), nullable=False, comment='查询类型'),
    sa.Column('query_config', sa.Text(), nullable=True, comment='查询配置'),
    sa.Column('display_config', sa.Text(), nullable=True, comment='显示配置'),
    sa.Column('status_config', sa.Text(), nullable=True, comment='状态配置'),
    sa.Column('chart_config', sa.Text(), nullable=True, comment='图表配置'),
    sa.Column('required_permission', sa.String(length=50), nullable=True, comment='所需权限'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='访问次数'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据视图配置表'
    )
    op.create_index('ix_lens_views_category', 'lens_views', ['category_id'], unique=False)
    op.create_index('ix_lens_views_created_by', 'lens_views', ['created_by'], unique=False)
    op.create_index('ix_lens_views_datasource', 'lens_views', ['datasource_id'], unique=False)
    op.create_table('map_markers',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='标记点名称'),
    sa.Column('lat', sa.Float(), nullable=False, comment='纬度'),
    sa.Column('lng', sa.Float(), nullable=False, comment='经度'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='标记点颜色'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标类名'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述/备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户自定义地理标记点表'
    )
    op.create_index(op.f('ix_map_markers_id'), 'map_markers', ['id'], unique=False)
    op.create_index(op.f('ix_map_markers_user_id'), 'map_markers', ['user_id'], unique=False)
    op.create_table('map_tile_sources',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='源标识名称'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='瓦片物理路径'),
    sa.Column('min_zoom', sa.Integer(), nullable=True, comment='最小缩放'),
    sa.Column('max_zoom', sa.Integer(), nullable=True, comment='最大缩放'),
    sa.Column('bounds', sa.JSON(), nullable=True, comment='地理范围边界 [[lat_min, lng_min], [lat_max, lng_max]]'),
    sa.Column('center', sa.JSON(), nullable=True, comment='默认推荐中心点 [lat, lng]'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='入库时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='离线瓦片资源元数据表'
    )
    op.create_index(op.f('ix_map_tile_sources_id'), 'map_tile_sources', ['id'], unique=False)
    op.create_table('map_trails',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='所属用户ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='显示文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='物理存储相对路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小字节'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型如 gpx, csv'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='轨迹显示颜色'),
    sa.Column('is_visible', sa.Boolean(), nullable=True, comment='是否默认可见'),
    sa.Column('is_favorite', sa.Boolean(), nullable=True, comment='是否收藏'),
    sa.Column('stats', sa.JSON(), nullable=True, comment='轨迹统计信息如里程、海拔等'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='地图轨迹元数据及样式持久化表'
    )
    op.create_index(op.f('ix_map_trails_id'), 'map_trails', ['id'], unique=False)
    op.create_index(op.f('ix_map_trails_user_id'), 'map_trails', ['user_id'], unique=False)
    op.create_table('notes_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='文件夹名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父文件夹ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['notes_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='笔记文件夹表'
    )
    op.create_index(op.f('ix_notes_folders_parent_id'), 'notes_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_notes_folders_user_id'), 'notes_folders', ['user_id'], unique=False)
    op.create_table('notes_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称'),
    sa.Column('color', sa.String(length=20), nullable=False, comment='标签颜色'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='笔记标签表'
    )
    op.create_index(op.f('ix_notes_tags_user_id'), 'notes_tags', ['user_id'], unique=False)
    op.create_table('sys_backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('backup_type', sa.String(length=20), nullable=False, comment='备份类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='备份状态'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='备份文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='备份文件大小(字节)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备份描述'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统备份记录表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='日志级别'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='模块名称'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型'),
    sa.Column('message', sa.Text(), nullable=True, comment='日志内容'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='请求方法'),
    sa.Column('request_path', sa.String(length=500), nullable=True, comment='请求路径'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统审计日志表'
    )
    op.create_index(op.f('ix_sys_logs_action'), 'sys_logs', ['action'], unique=False)
    op.create_index(op.f('ix_sys_logs_created_at'), 'sys_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_logs_level'), 'sys_logs', ['level'], unique=False)
    op.create_index(op.f('ix_sys_logs_module'), 'sys_logs', ['module'], unique=False)
    op.create_index(op.f('ix_sys_logs_user_id'), 'sys_logs', ['user_id'], unique=False)
    op.create_table('sys_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('metric_type', sa.String(length=50), nullable=False, comment='指标类型'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment='指标名称'),
    sa.Column('value', sa.Float(), nullable=False, comment='指标值'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='额外元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统性能指标表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_module_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('module_id', sa.String(length=50), nullable=False, comment='模块ID'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('config', sa.JSON(), nullable=True, comment='配置内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='模块启用状态与配置表'
    )
    op.create_index(op.f('ix_sys_module_configs_module_id'), 'sys_module_configs', ['module_id'], unique=True)
    op.create_table('sys_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.JSON(), nullable=True, comment='配置值'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置项表'
    )
    op.create_index(op.f('ix_sys_settings_key'), 'sys_settings', ['key'], unique=True)
    op.create_table('sys_user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='组名称'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='权限列表'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户组/权限模板表'
    )
    op.create_index(op.f('ix_sys_user_groups_name'), 'sys_user_groups', ['name'], unique=True)
    op.create_table('sys_user_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('module_id', sa.String(length=50), nullable=False, comment='模块ID'),
    sa.Column('installed', sa.Boolean(), nullable=False, comment='用户是否安装'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='用户是否启用'),
    sa.Column('installed_at', sa.DateTime(), nullable=True, comment='安装时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module'),
    comment='用户个人模块安装与启用状态表'
    )
    op.create_index(op.f('ix_sys_user_modules_module_id'), 'sys_user_modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_sys_user_modules_user_id'), 'sys_user_modules', ['user_id'], unique=False)
    op.create_table('sys_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号码'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='权限列表'),
    sa.Column('role_ids', sa.JSON(), nullable=True, comment='角色ID列表'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='个性化设置'),
    sa.Column('storage_quota', sa.BigInteger(), nullable=True, comment='存储配额(字节)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    comment='系统用户表'
    )
    op.create_index(op.f('ix_sys_users_username'), 'sys_users', ['username'], unique=True)
    op.create_table('vault_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('icon', sa.String(length=50), nullable=False, comment='分类图标'),
    sa.Column('color', sa.String(length=20), nullable=False, comment='分类颜色'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='密码分类表'
    )
    op.create_index(op.f('ix_vault_categories_user_id'), 'vault_categories', ['user_id'], unique=False)
    op.create_table('vault_master_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('master_key_hash', sa.String(length=255), nullable=False, comment='主密码哈希'),
    sa.Column('salt', sa.String(length=64), nullable=False, comment='加密盐值'),
    sa.Column('verification_hash', sa.String(length=255), nullable=False, comment='验证哈希'),
    sa.Column('recovery_salt', sa.String(length=64), nullable=True, comment='恢复码盐值'),
    sa.Column('encrypted_data_key', sa.Text(), nullable=True, comment='用恢复码加密的数据密钥'),
    sa.Column('failed_attempts', sa.Integer(), nullable=False, comment='连续失败尝试次数'),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='是否已锁定'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户主密钥表'
    )
    op.create_index(op.f('ix_vault_master_keys_user_id'), 'vault_master_keys', ['user_id'], unique=True)
    op.create_table('video_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='视频集名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频集描述'),
    sa.Column('cover_video_id', sa.Integer(), nullable=True, comment='封面视频ID'),
    sa.Column('video_count', sa.Integer(), nullable=True, comment='视频数量'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='视频集表'
    )
    op.create_index(op.f('ix_video_collections_user_id'), 'video_collections', ['user_id'], unique=False)
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='提供者: local/online'),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True, comment='知识库ID'),
    sa.Column('use_analysis', sa.Boolean(), nullable=False, comment='是否使用数据分析'),
    sa.Column('config', sa.JSON(), nullable=True, comment='会话配置'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='AI对话会话表'
    )
    op.create_index('idx_ai_session_user_updated', 'ai_chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('album_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('album_id', sa.Integer(), nullable=False, comment='所属相册ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='存储路径'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True, comment='缩略图路径'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='照片标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='照片描述'),
    sa.Column('width', sa.Integer(), nullable=True, comment='图片宽度'),
    sa.Column('height', sa.Integer(), nullable=True, comment='图片高度'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=50), nullable=True, comment='MIME类型'),
    sa.Column('taken_at', sa.DateTime(), nullable=True, comment='拍摄时间'),
    sa.Column('camera_model', sa.String(length=100), nullable=True, comment='相机型号'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='上传时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['album_id'], ['album_albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='照片表'
    )
    op.create_index(op.f('ix_album_photos_album_id'), 'album_photos', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_photos_user_id'), 'album_photos', ['user_id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文章标题'),
    sa.Column('slug', sa.String(length=200), nullable=False, comment='文章别名/路径'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('cover', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者用户ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：draft草稿, published已发布, archived已归档'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('views', sa.Integer(), nullable=False, comment='阅读量'),
    sa.Column('likes', sa.Integer(), nullable=False, comment='点赞量'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='博客文章表'
    )
    op.create_index(op.f('ix_blog_posts_author_id'), 'blog_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_table('course_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='课程标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='课程描述'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='封面图片'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='课程分类'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='难度: beginner/intermediate/advanced'),
    sa.Column('duration_hours', sa.Float(), nullable=False, comment='预计学时（小时）'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否发布'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='课程表'
    )
    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('bank_id', sa.Integer(), nullable=True, comment='所属题库ID'),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment='题目类型'),
    sa.Column('title', sa.Text(), nullable=False, comment='题干'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项列表(JSON)'),
    sa.Column('answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('analysis', sa.Text(), nullable=True, comment='答案解析'),
    sa.Column('score', sa.Float(), nullable=True, comment='分值'),
    sa.Column('difficulty', sa.Integer(), nullable=True, comment='难度等级(1-5)'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签(逗号分隔)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['bank_id'], ['exam_question_banks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='考试题目表'
    )
    op.create_index(op.f('ix_exam_questions_bank_id'), 'exam_questions', ['bank_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_user_id'), 'exam_questions', ['user_id'], unique=False)
    op.create_table('exam_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='考生ID'),
    sa.Column('paper_id', sa.Integer(), nullable=False, comment='试卷ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='考试状态'),
    sa.Column('score', sa.Float(), nullable=True, comment='得分'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='总分'),
    sa.Column('is_passed', sa.Boolean(), nullable=True, comment='是否及格'),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='正确数量'),
    sa.Column('wrong_count', sa.Integer(), nullable=True, comment='错误数量'),
    sa.Column('unanswered_count', sa.Integer(), nullable=True, comment='未答数量'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('submit_time', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('used_seconds', sa.Integer(), nullable=True, comment='用时(秒)'),
    sa.Column('grader_id', sa.Integer(), nullable=True, comment='阅卷人ID'),
    sa.Column('graded_at', sa.DateTime(), nullable=True, comment='阅卷时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='阅卷评语'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='考试记录表'
    )
    op.create_index(op.f('ix_exam_records_paper_id'), 'exam_records', ['paper_id'], unique=False)
    op.create_index(op.f('ix_exam_records_user_id'), 'exam_records', ['user_id'], unique=False)
    op.create_table('feedback_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='反馈标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='反馈内容'),
    sa.Column('type', sa.Enum('SUGGESTION', 'OPINION', 'BUG', 'FEATURE', 'OTHER', name='feedbacktype'), nullable=False, comment='反馈类型'),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='feedbackpriority'), nullable=False, comment='优先级'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='提交用户ID'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'RESOLVED', 'CLOSED', name='feedbackstatus'), nullable=False, comment='处理状态'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人ID'),
    sa.Column('reply_content', sa.Text(), nullable=True, comment='回复内容'),
    sa.Column('reply_at', sa.DateTime(), nullable=True, comment='回复时间'),
    sa.Column('contact', sa.String(length=100), nullable=True, comment='联系方式'),
    sa.Column('attachments', sa.String(length=500), nullable=True, comment='附件路径'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='解决时间'),
    sa.ForeignKeyConstraint(['handler_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='反馈表'
    )
    op.create_index(op.f('ix_feedback_feedbacks_status'), 'feedback_feedbacks', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_feedbacks_user_id'), 'feedback_feedbacks', ['user_id'], unique=False)
    op.create_table('fm_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件夹名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父文件夹ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('path', sa.String(length=1024), nullable=False, comment='完整路径'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['fm_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件管理虚拟文件夹表'
    )
    op.create_index('idx_fm_folder_parent', 'fm_folders', ['parent_id'], unique=False)
    op.create_index('idx_fm_folder_user', 'fm_folders', ['user_id'], unique=False)
    op.create_table('im_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('contact_id', sa.Integer(), nullable=False, comment='联系人ID'),
    sa.Column('alias', sa.String(length=50), nullable=True, comment='备注名'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['contact_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='即时通讯联系人表'
    )
    op.create_index('idx_im_contact_user_contact', 'im_contacts', ['user_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_im_contacts_contact_id'), 'im_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_im_contacts_user_id'), 'im_contacts', ['user_id'], unique=False)
    op.create_table('im_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='会话类型'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='会话名称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='会话头像'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='群主ID'),
    sa.Column('last_message_id', sa.Integer(), nullable=True, comment='最后消息ID'),
    sa.Column('last_message_time', sa.DateTime(timezone=True), nullable=True, comment='最后消息时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='即时通讯会话表'
    )
    op.create_index('idx_im_conv_updated', 'im_conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_im_conversations_type'), 'im_conversations', ['type'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.String(length=200), nullable=False, comment='描述'),
    sa.Column('cover', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='所有者ID'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库列表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('map_configs',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='所属用户ID'),
    sa.Column('map_mode', sa.String(length=20), nullable=True, comment='底图模式: online/offline'),
    sa.Column('tile_source', sa.String(length=100), nullable=True, comment='当前离线源名称'),
    sa.Column('online_tile_url', sa.String(length=500), nullable=True, comment='在线底图模板URL'),
    sa.Column('last_center', sa.JSON(), nullable=True, comment='上次查看中心坐标 [lat, lng]'),
    sa.Column('last_zoom', sa.Integer(), nullable=True, comment='上次缩放级别'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户地图个性化配置表'
    )
    op.create_index(op.f('ix_map_configs_id'), 'map_configs', ['id'], unique=False)
    op.create_index(op.f('ix_map_configs_user_id'), 'map_configs', ['user_id'], unique=True)
    op.create_table('notes_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('folder_id', sa.Integer(), nullable=True, comment='所属文件夹ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('is_starred', sa.Boolean(), nullable=False, comment='是否收藏'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['folder_id'], ['notes_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='笔记内容表'
    )
    op.create_index(op.f('ix_notes_notes_folder_id'), 'notes_notes', ['folder_id'], unique=False)
    op.create_index(op.f('ix_notes_notes_user_id'), 'notes_notes', ['user_id'], unique=False)
    op.create_table('schedule_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('color', sa.String(length=20), nullable=False, comment='分类颜色'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='分类图标'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='日程分类表'
    )
    op.create_table('schedule_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='日程标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='开始日期'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='开始时间'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='结束时间'),
    sa.Column('is_all_day', sa.Boolean(), nullable=False, comment='是否全天事件'),
    sa.Column('event_type', sa.String(length=20), nullable=False, comment='事件类型'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='自定义颜色'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='地点'),
    sa.Column('repeat_type', sa.String(length=20), nullable=False, comment='重复类型'),
    sa.Column('repeat_end_date', sa.Date(), nullable=True, comment='重复结束日期'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='是否已完成'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='日程事件表'
    )
    op.create_table('sys_announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否发布'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('start_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('views', sa.Integer(), nullable=False, comment='浏览次数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='系统公告表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sys_announcements_author_id'), 'sys_announcements', ['author_id'], unique=False)
    op.create_table('sys_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('uploader_id', sa.Integer(), nullable=True, comment='上传者ID'),
    sa.Column('category', sa.String(length=50), server_default='attachment', nullable=False, comment='业务分类'),
    sa.Column('ref_id', sa.Integer(), nullable=True, comment='关联业务ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['uploader_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文件存储记录表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收用户ID'),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送者ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='通知类型'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='阅读时间'),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='操作链接'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['sender_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='系统通知表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transfer_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('direction', sa.String(length=16), nullable=False, comment='传输方向(send/receive)'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='传输状态'),
    sa.Column('peer_id', sa.Integer(), nullable=True, comment='对方用户ID'),
    sa.Column('peer_nickname', sa.String(length=64), nullable=True, comment='对方昵称（冗余存储）'),
    sa.Column('peer_device', sa.String(length=128), nullable=True, comment='对方设备信息'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_type', sa.String(length=64), nullable=True, comment='文件MIME类型'),
    sa.Column('file_count', sa.Integer(), nullable=True, comment='文件数量'),
    sa.Column('success', sa.Boolean(), nullable=True, comment='是否成功'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='传输耗时(毫秒)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['peer_id'], ['sys_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='快传历史记录表'
    )
    op.create_table('transfer_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('session_code', sa.String(length=16), nullable=False, comment='传输码'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='发送方用户ID'),
    sa.Column('sender_device', sa.String(length=128), nullable=True, comment='发送方设备信息'),
    sa.Column('receiver_id', sa.Integer(), nullable=True, comment='接收方用户ID'),
    sa.Column('receiver_device', sa.String(length=128), nullable=True, comment='接收方设备信息'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='会话状态'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_type', sa.String(length=64), nullable=True, comment='文件MIME类型'),
    sa.Column('file_count', sa.Integer(), nullable=True, comment='文件数量'),
    sa.Column('transferred_bytes', sa.BigInteger(), nullable=True, comment='已传输字节数'),
    sa.Column('total_chunks', sa.Integer(), nullable=True, comment='总分块数'),
    sa.Column('completed_chunks', sa.Integer(), nullable=True, comment='已完成分块数'),
    sa.Column('temp_file_path', sa.String(length=512), nullable=True, comment='临时文件存储路径'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True, comment='连接时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.ForeignKeyConstraint(['receiver_id'], ['sys_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['sys_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='快传会话表'
    )
    op.create_index(op.f('ix_transfer_sessions_session_code'), 'transfer_sessions', ['session_code'], unique=True)
    op.create_table('vault_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='条目标题'),
    sa.Column('website', sa.String(length=500), nullable=True, comment='网站地址'),
    sa.Column('username_encrypted', sa.Text(), nullable=False, comment='加密的用户名'),
    sa.Column('password_encrypted', sa.Text(), nullable=False, comment='加密的密码'),
    sa.Column('notes_encrypted', sa.Text(), nullable=True, comment='加密的备注'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('is_starred', sa.Boolean(), nullable=False, comment='是否收藏'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['vault_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='密码条目表'
    )
    op.create_index(op.f('ix_vault_items_category_id'), 'vault_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_vault_items_user_id'), 'vault_items', ['user_id'], unique=False)
    op.create_table('video_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('collection_id', sa.Integer(), nullable=False, comment='所属视频集ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='存储路径'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True, comment='缩略图路径'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='视频标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频描述'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='时长(秒)'),
    sa.Column('width', sa.Integer(), nullable=True, comment='视频宽度'),
    sa.Column('height', sa.Integer(), nullable=True, comment='视频高度'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=50), nullable=True, comment='MIME类型'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='上传时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['collection_id'], ['video_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='视频表'
    )
    op.create_index(op.f('ix_video_videos_collection_id'), 'video_videos', ['collection_id'], unique=False)
    op.create_index(op.f('ix_video_videos_user_id'), 'video_videos', ['user_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('is_error', sa.Boolean(), nullable=False, comment='是否为错误消息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI对话消息表'
    )
    op.create_index('idx_ai_msg_session_created', 'ai_chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_table('blog_post_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章与标签关联表'
    )
    op.create_table('course_chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='所属课程ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='章节标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='章节内容（Markdown）'),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='视频链接'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='章节时长（分钟）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['course_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='课程章节表'
    )
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('progress', sa.Float(), nullable=False, comment='学习进度 0-100'),
    sa.Column('last_chapter_id', sa.Integer(), nullable=True, comment='上次学习的章节ID'),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False, comment='报名时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['course_id'], ['course_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='课程报名记录表'
    )
    op.create_table('exam_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='考试记录ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('user_answer', sa.Text(), nullable=True, comment='用户答案'),
    sa.Column('correct_answer', sa.Text(), nullable=True, comment='正确答案'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确'),
    sa.Column('score', sa.Float(), nullable=True, comment='得分'),
    sa.Column('max_score', sa.Float(), nullable=True, comment='满分'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评语'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['record_id'], ['exam_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='答题记录表'
    )
    op.create_index(op.f('ix_exam_answers_question_id'), 'exam_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_answers_record_id'), 'exam_answers', ['record_id'], unique=False)
    op.create_table('exam_cheat_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='考试记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='行为类型'),
    sa.Column('count', sa.Integer(), nullable=True, comment='累计次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='记录时间'),
    sa.ForeignKeyConstraint(['record_id'], ['exam_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='作弊日志表'
    )
    op.create_index(op.f('ix_exam_cheat_logs_record_id'), 'exam_cheat_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_exam_cheat_logs_user_id'), 'exam_cheat_logs', ['user_id'], unique=False)
    op.create_table('exam_paper_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('paper_id', sa.Integer(), nullable=False, comment='试卷ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('score', sa.Float(), nullable=True, comment='本题分值(可覆盖题目默认分值)'),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='试卷题目表'
    )
    op.create_index(op.f('ix_exam_paper_questions_paper_id'), 'exam_paper_questions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_exam_paper_questions_question_id'), 'exam_paper_questions', ['question_id'], unique=False)
    op.create_table('exam_wrong_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('paper_id', sa.Integer(), nullable=True, comment='来源试卷ID'),
    sa.Column('user_answer', sa.Text(), nullable=True, comment='用户的错误答案'),
    sa.Column('correct_answer', sa.Text(), nullable=True, comment='正确答案'),
    sa.Column('wrong_count', sa.Integer(), nullable=True, comment='错误次数'),
    sa.Column('first_wrong_at', sa.DateTime(timezone=True), nullable=True, comment='首次错误时间'),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=True, comment='最近错误时间'),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='错题本表'
    )
    op.create_index(op.f('ix_exam_wrong_questions_question_id'), 'exam_wrong_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_wrong_questions_user_id'), 'exam_wrong_questions', ['user_id'], unique=False)
    op.create_table('fm_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('folder_id', sa.Integer(), nullable=True, comment='所属文件夹ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('storage_path', sa.String(length=512), nullable=False, comment='物理存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=128), nullable=True, comment='MIME类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件描述'),
    sa.Column('is_starred', sa.Boolean(), nullable=True, comment='是否收藏'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['folder_id'], ['fm_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件管理虚拟文件表'
    )
    op.create_index('idx_fm_file_folder', 'fm_files', ['folder_id'], unique=False)
    op.create_index('idx_fm_file_name', 'fm_files', ['name'], unique=False)
    op.create_index('idx_fm_file_user', 'fm_files', ['user_id'], unique=False)
    op.create_table('im_conversation_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色'),
    sa.Column('unread_count', sa.Integer(), nullable=False, comment='未读数'),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True, comment='最后已读消息ID'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('is_muted', sa.Boolean(), nullable=False, comment='是否免打扰'),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False, comment='加入时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['im_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='即时通讯会话成员表'
    )
    op.create_index('idx_im_member_conv_user', 'im_conversation_members', ['conversation_id', 'user_id'], unique=False)
    op.create_index('idx_im_member_user', 'im_conversation_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_im_conversation_members_conversation_id'), 'im_conversation_members', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_im_conversation_members_user_id'), 'im_conversation_members', ['user_id'], unique=False)
    op.create_table('im_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='发送者ID'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='消息类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件路径'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小'),
    sa.Column('file_mime', sa.String(length=100), nullable=True, comment='文件MIME类型'),
    sa.Column('reply_to_id', sa.Integer(), nullable=True, comment='回复消息ID'),
    sa.Column('is_recalled', sa.Boolean(), nullable=False, comment='是否撤回'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='发送时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['im_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['im_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='即时通讯消息表'
    )
    op.create_index('idx_im_msg_conv_created', 'im_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_im_msg_sender', 'im_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_im_messages_conversation_id'), 'im_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_im_messages_created_at'), 'im_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_im_messages_sender_id'), 'im_messages', ['sender_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('base_id', sa.Integer(), nullable=False, comment='所属知识库ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父节点ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('node_type', sa.String(length=20), nullable=False, comment='节点类型'),
    sa.Column('content', sa.Text(), nullable=True, comment='文档内容'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('file_meta', sa.JSON(), nullable=False, comment='文件元数据'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库节点表',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notes_note_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('note_id', sa.Integer(), nullable=False, comment='笔记ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.ForeignKeyConstraint(['note_id'], ['notes_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['notes_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='笔记与标签关联表'
    )
    op.create_index(op.f('ix_notes_note_tags_note_id'), 'notes_note_tags', ['note_id'], unique=False)
    op.create_index(op.f('ix_notes_note_tags_tag_id'), 'notes_note_tags', ['tag_id'], unique=False)
    op.create_table('schedule_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('event_id', sa.Integer(), nullable=False, comment='关联日程ID'),
    sa.Column('remind_before_minutes', sa.Integer(), nullable=False, comment='提前提醒分钟数'),
    sa.Column('remind_time', sa.DateTime(), nullable=False, comment='提醒时间'),
    sa.Column('is_sent', sa.Boolean(), nullable=False, comment='是否已发送'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.ForeignKeyConstraint(['event_id'], ['schedule_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='日程提醒表'
    )
    op.create_table('transfer_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='分块索引（从0开始）'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分块大小(字节)'),
    sa.Column('chunk_hash', sa.String(length=64), nullable=True, comment='分块MD5哈希'),
    sa.Column('uploaded', sa.Boolean(), nullable=True, comment='是否已上传'),
    sa.Column('verified', sa.Boolean(), nullable=True, comment='是否已验证'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True, comment='上传时间'),
    sa.ForeignKeyConstraint(['session_id'], ['transfer_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='快传分块表'
    )
    op.create_table('course_chapter_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('chapter_id', sa.Integer(), nullable=False, comment='章节ID'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='是否完成'),
    sa.Column('progress_seconds', sa.Integer(), nullable=False, comment='视频播放进度（秒）'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='章节学习进度表'
    )
    op.create_table('im_message_reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='消息ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False, comment='阅读时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['im_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['im_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='即时通讯消息已读记录表'
    )
    op.create_index('idx_im_read_msg_user', 'im_message_reads', ['message_id', 'user_id'], unique=False)
    op.create_index('idx_im_read_user_conv', 'im_message_reads', ['user_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_im_message_reads_conversation_id'), 'im_message_reads', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_im_message_reads_message_id'), 'im_message_reads', ['message_id'], unique=False)
    op.create_index(op.f('ix_im_message_reads_user_id'), 'im_message_reads', ['user_id'], unique=False)
    op.create_table('knowledge_entities',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('base_id', sa.Integer(), nullable=False, comment='所属知识库ID'),
    sa.Column('node_id', sa.Integer(), nullable=False, comment='关联节点ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='实体名称'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='实体类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识实体表'
    )
    op.create_table('knowledge_relations',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('base_id', sa.Integer(), nullable=False, comment='所属知识库ID'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='源实体ID'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='目标实体ID'),
    sa.Column('relation_type', sa.String(length=100), nullable=False, comment='关系类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='关系描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识关系表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_relations')
    op.drop_table('knowledge_entities')
    op.drop_index(op.f('ix_im_message_reads_user_id'), table_name='im_message_reads')
    op.drop_index(op.f('ix_im_message_reads_message_id'), table_name='im_message_reads')
    op.drop_index(op.f('ix_im_message_reads_conversation_id'), table_name='im_message_reads')
    op.drop_index('idx_im_read_user_conv', table_name='im_message_reads')
    op.drop_index('idx_im_read_msg_user', table_name='im_message_reads')
    op.drop_table('im_message_reads')
    op.drop_table('course_chapter_progress')
    op.drop_table('transfer_chunks')
    op.drop_table('schedule_reminders')
    op.drop_index(op.f('ix_notes_note_tags_tag_id'), table_name='notes_note_tags')
    op.drop_index(op.f('ix_notes_note_tags_note_id'), table_name='notes_note_tags')
    op.drop_table('notes_note_tags')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_im_messages_sender_id'), table_name='im_messages')
    op.drop_index(op.f('ix_im_messages_created_at'), table_name='im_messages')
    op.drop_index(op.f('ix_im_messages_conversation_id'), table_name='im_messages')
    op.drop_index('idx_im_msg_sender', table_name='im_messages')
    op.drop_index('idx_im_msg_conv_created', table_name='im_messages')
    op.drop_table('im_messages')
    op.drop_index(op.f('ix_im_conversation_members_user_id'), table_name='im_conversation_members')
    op.drop_index(op.f('ix_im_conversation_members_conversation_id'), table_name='im_conversation_members')
    op.drop_index('idx_im_member_user', table_name='im_conversation_members')
    op.drop_index('idx_im_member_conv_user', table_name='im_conversation_members')
    op.drop_table('im_conversation_members')
    op.drop_index('idx_fm_file_user', table_name='fm_files')
    op.drop_index('idx_fm_file_name', table_name='fm_files')
    op.drop_index('idx_fm_file_folder', table_name='fm_files')
    op.drop_table('fm_files')
    op.drop_index(op.f('ix_exam_wrong_questions_user_id'), table_name='exam_wrong_questions')
    op.drop_index(op.f('ix_exam_wrong_questions_question_id'), table_name='exam_wrong_questions')
    op.drop_table('exam_wrong_questions')
    op.drop_index(op.f('ix_exam_paper_questions_question_id'), table_name='exam_paper_questions')
    op.drop_index(op.f('ix_exam_paper_questions_paper_id'), table_name='exam_paper_questions')
    op.drop_table('exam_paper_questions')
    op.drop_index(op.f('ix_exam_cheat_logs_user_id'), table_name='exam_cheat_logs')
    op.drop_index(op.f('ix_exam_cheat_logs_record_id'), table_name='exam_cheat_logs')
    op.drop_table('exam_cheat_logs')
    op.drop_index(op.f('ix_exam_answers_record_id'), table_name='exam_answers')
    op.drop_index(op.f('ix_exam_answers_question_id'), table_name='exam_answers')
    op.drop_table('exam_answers')
    op.drop_table('course_enrollments')
    op.drop_table('course_chapters')
    op.drop_table('blog_post_tags')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_index('idx_ai_msg_session_created', table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_video_videos_user_id'), table_name='video_videos')
    op.drop_index(op.f('ix_video_videos_collection_id'), table_name='video_videos')
    op.drop_table('video_videos')
    op.drop_index(op.f('ix_vault_items_user_id'), table_name='vault_items')
    op.drop_index(op.f('ix_vault_items_category_id'), table_name='vault_items')
    op.drop_table('vault_items')
    op.drop_index(op.f('ix_transfer_sessions_session_code'), table_name='transfer_sessions')
    op.drop_table('transfer_sessions')
    op.drop_table('transfer_history')
    op.drop_table('sys_notifications')
    op.drop_table('sys_files')
    op.drop_index(op.f('ix_sys_announcements_author_id'), table_name='sys_announcements')
    op.drop_table('sys_announcements')
    op.drop_table('schedule_events')
    op.drop_table('schedule_categories')
    op.drop_index(op.f('ix_notes_notes_user_id'), table_name='notes_notes')
    op.drop_index(op.f('ix_notes_notes_folder_id'), table_name='notes_notes')
    op.drop_table('notes_notes')
    op.drop_index(op.f('ix_map_configs_user_id'), table_name='map_configs')
    op.drop_index(op.f('ix_map_configs_id'), table_name='map_configs')
    op.drop_table('map_configs')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_im_conversations_type'), table_name='im_conversations')
    op.drop_index('idx_im_conv_updated', table_name='im_conversations')
    op.drop_table('im_conversations')
    op.drop_index(op.f('ix_im_contacts_user_id'), table_name='im_contacts')
    op.drop_index(op.f('ix_im_contacts_contact_id'), table_name='im_contacts')
    op.drop_index('idx_im_contact_user_contact', table_name='im_contacts')
    op.drop_table('im_contacts')
    op.drop_index('idx_fm_folder_user', table_name='fm_folders')
    op.drop_index('idx_fm_folder_parent', table_name='fm_folders')
    op.drop_table('fm_folders')
    op.drop_index(op.f('ix_feedback_feedbacks_user_id'), table_name='feedback_feedbacks')
    op.drop_index(op.f('ix_feedback_feedbacks_status'), table_name='feedback_feedbacks')
    op.drop_table('feedback_feedbacks')
    op.drop_index(op.f('ix_exam_records_user_id'), table_name='exam_records')
    op.drop_index(op.f('ix_exam_records_paper_id'), table_name='exam_records')
    op.drop_table('exam_records')
    op.drop_index(op.f('ix_exam_questions_user_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_bank_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_table('course_courses')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_author_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_album_photos_user_id'), table_name='album_photos')
    op.drop_index(op.f('ix_album_photos_album_id'), table_name='album_photos')
    op.drop_table('album_photos')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index('idx_ai_session_user_updated', table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_index(op.f('ix_video_collections_user_id'), table_name='video_collections')
    op.drop_table('video_collections')
    op.drop_index(op.f('ix_vault_master_keys_user_id'), table_name='vault_master_keys')
    op.drop_table('vault_master_keys')
    op.drop_index(op.f('ix_vault_categories_user_id'), table_name='vault_categories')
    op.drop_table('vault_categories')
    op.drop_index(op.f('ix_sys_users_username'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_sys_user_modules_user_id'), table_name='sys_user_modules')
    op.drop_index(op.f('ix_sys_user_modules_module_id'), table_name='sys_user_modules')
    op.drop_table('sys_user_modules')
    op.drop_index(op.f('ix_sys_user_groups_name'), table_name='sys_user_groups')
    op.drop_table('sys_user_groups')
    op.drop_index(op.f('ix_sys_settings_key'), table_name='sys_settings')
    op.drop_table('sys_settings')
    op.drop_index(op.f('ix_sys_module_configs_module_id'), table_name='sys_module_configs')
    op.drop_table('sys_module_configs')
    op.drop_table('sys_metrics')
    op.drop_index(op.f('ix_sys_logs_user_id'), table_name='sys_logs')
    op.drop_index(op.f('ix_sys_logs_module'), table_name='sys_logs')
    op.drop_index(op.f('ix_sys_logs_level'), table_name='sys_logs')
    op.drop_index(op.f('ix_sys_logs_created_at'), table_name='sys_logs')
    op.drop_index(op.f('ix_sys_logs_action'), table_name='sys_logs')
    op.drop_table('sys_logs')
    op.drop_table('sys_backups')
    op.drop_index(op.f('ix_notes_tags_user_id'), table_name='notes_tags')
    op.drop_table('notes_tags')
    op.drop_index(op.f('ix_notes_folders_user_id'), table_name='notes_folders')
    op.drop_index(op.f('ix_notes_folders_parent_id'), table_name='notes_folders')
    op.drop_table('notes_folders')
    op.drop_index(op.f('ix_map_trails_user_id'), table_name='map_trails')
    op.drop_index(op.f('ix_map_trails_id'), table_name='map_trails')
    op.drop_table('map_trails')
    op.drop_index(op.f('ix_map_tile_sources_id'), table_name='map_tile_sources')
    op.drop_table('map_tile_sources')
    op.drop_index(op.f('ix_map_markers_user_id'), table_name='map_markers')
    op.drop_index(op.f('ix_map_markers_id'), table_name='map_markers')
    op.drop_table('map_markers')
    op.drop_index('ix_lens_views_datasource', table_name='lens_views')
    op.drop_index('ix_lens_views_created_by', table_name='lens_views')
    op.drop_index('ix_lens_views_category', table_name='lens_views')
    op.drop_table('lens_views')
    op.drop_index('ix_lens_recent_user', table_name='lens_recent_views')
    op.drop_index('ix_lens_recent_time', table_name='lens_recent_views')
    op.drop_table('lens_recent_views')
    op.drop_index('ix_lens_favorites_view', table_name='lens_favorites')
    op.drop_index('ix_lens_favorites_user', table_name='lens_favorites')
    op.drop_table('lens_favorites')
    op.drop_index('ix_lens_datasources_name', table_name='lens_datasources')
    op.drop_table('lens_datasources')
    op.drop_index('ix_lens_categories_order', table_name='lens_categories')
    op.drop_table('lens_categories')
    op.drop_index(op.f('ix_exam_question_banks_user_id'), table_name='exam_question_banks')
    op.drop_table('exam_question_banks')
    op.drop_index(op.f('ix_exam_papers_user_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    op.drop_index(op.f('ix_blog_tags_slug'), table_name='blog_tags')
    op.drop_table('blog_tags')
    op.drop_index(op.f('ix_blog_categories_slug'), table_name='blog_categories')
    op.drop_table('blog_categories')
    op.drop_table('analysis_smart_tables')
    op.drop_table('analysis_smart_table_data')
    op.drop_table('analysis_models')
    op.drop_table('analysis_datasets')
    op.drop_table('analysis_dashboards')
    op.drop_table('analysis_charts')
    op.drop_index(op.f('ix_album_albums_user_id'), table_name='album_albums')
    op.drop_table('album_albums')
    # ### end Alembic commands ###







