"""add_vault_tables

Revision ID: 4e3138b5bab4
Revises: af6011a6de52
Create Date: 2026-01-17 16:23:50.455043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3138b5bab4'
down_revision: Union[str, None] = 'af6011a6de52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###







