"""add table comment to map_trails

Revision ID: 50cd8de9681c
Revises: 7be85927b5f2
Create Date: 2026-01-03 22:52:16.447205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50cd8de9681c'
down_revision: Union[str, None] = '7be85927b5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_comment='报告全文',
               existing_nullable=True)
    op.alter_column('map_trails', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('map_trails', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.create_table_comment(
        'map_trails',
        '地图轨迹元数据及样式持久化表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_table_comment(
        'map_trails',
        existing_comment='地图轨迹元数据及样式持久化表',
        schema=None
    )
    op.alter_column('map_trails', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('map_trails', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_comment='报告全文',
               existing_nullable=True)
    # ### end Alembic commands ###







