"""add_album_module_tables

Revision ID: 5da3e4b569bc
Revises: 15cb3d79a241
Create Date: 2026-01-03 16:10:38.936361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5da3e4b569bc'
down_revision: Union[str, None] = '15cb3d79a241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_album_items_user_id', table_name='album_items')
    op.drop_table('album_items')
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('im_contacts', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'role',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'unread_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'is_muted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('im_conversations', 'type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('im_messages', 'type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('im_messages', 'is_recalled',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.create_table_comment(
        'sys_notifications',
        '系统通知表',
        existing_comment='系统信息表',
        schema=None
    )
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.create_table_comment(
        'sys_notifications',
        '系统信息表',
        existing_comment='系统通知表',
        schema=None
    )
    op.alter_column('im_messages', 'is_recalled',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('im_messages', 'type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'text'"),
               existing_nullable=False)
    op.alter_column('im_conversations', 'type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'private'"),
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'is_muted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'unread_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'role',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'member'"),
               existing_nullable=False)
    op.alter_column('im_contacts', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_table('album_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='所属用户ID'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='内容'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否启用'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_album_items_user_id', 'album_items', ['user_id'], unique=False)
    # ### end Alembic commands ###







