"""update database comments

Revision ID: 68d1ecd89ecd
Revises: ab8e62e3261c
Create Date: 2026-01-03 17:13:50.355170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68d1ecd89ecd'
down_revision: Union[str, None] = 'ab8e62e3261c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'album_albums',
        '相册表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'album_photos',
        '照片表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('analysis_charts', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_charts', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='图表名称',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'dataset_id',
               existing_type=mysql.INTEGER(),
               comment='关联数据集ID',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'chart_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='图表类型',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'config',
               existing_type=mysql.JSON(),
               comment='图表配置',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'description',
               existing_type=mysql.TEXT(),
               comment='图表描述',
               existing_nullable=True)
    op.alter_column('analysis_charts', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_dashboards', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_dashboards', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='仪表盘名称',
               existing_nullable=False)
    op.alter_column('analysis_dashboards', 'description',
               existing_type=mysql.TEXT(),
               comment='仪表盘描述',
               existing_nullable=True)
    op.alter_column('analysis_dashboards', 'widgets',
               existing_type=mysql.JSON(),
               comment='组件配置',
               existing_nullable=True)
    op.alter_column('analysis_dashboards', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_dashboards', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_datasets', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='数据集名称',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'source_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='来源类型',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'table_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='DuckDB表名',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'config',
               existing_type=mysql.JSON(),
               comment='导入配置',
               existing_nullable=True)
    op.alter_column('analysis_datasets', 'row_count',
               existing_type=mysql.INTEGER(),
               comment='数据行数',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_models', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_models', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='模型名称',
               existing_nullable=False)
    op.alter_column('analysis_models', 'description',
               existing_type=mysql.TEXT(),
               comment='模型描述',
               existing_nullable=True)
    op.alter_column('analysis_models', 'graph_config',
               existing_type=mysql.JSON(),
               comment='流程图配置',
               existing_nullable=True)
    op.alter_column('analysis_models', 'status',
               existing_type=mysql.VARCHAR(length=50),
               comment='状态',
               existing_nullable=False)
    op.alter_column('analysis_models', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_models', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_smart_report_records', 'report_id',
               existing_type=mysql.INTEGER(),
               comment='报告模板ID',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='记录名称',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'docx_file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='Word文件路径',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'pdf_file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='PDF文件路径',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               comment='报告全文',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_reports', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_smart_reports', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='模板名称',
               existing_nullable=False)
    op.alter_column('analysis_smart_reports', 'template_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='Word模板路径',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'content_html',
               existing_type=mysql.TEXT(),
               comment='HTML内容',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'content_md',
               existing_type=mysql.TEXT(),
               comment='Markdown内容',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'template_vars',
               existing_type=mysql.JSON(),
               comment='模板变量',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'dataset_id',
               existing_type=mysql.INTEGER(),
               comment='关联数据集ID',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'data_row',
               existing_type=mysql.VARCHAR(length=50),
               comment='数据行模式',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_reports', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_smart_table_data', 'table_id',
               existing_type=mysql.INTEGER(),
               comment='智能表格ID',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'row_data',
               existing_type=mysql.JSON(),
               comment='行数据',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_smart_tables', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='表格名称',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'fields',
               existing_type=mysql.JSON(),
               comment='字段定义',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'config',
               existing_type=mysql.JSON(),
               comment='表格配置',
               existing_nullable=True)
    op.alter_column('analysis_smart_tables', 'dataset_id',
               existing_type=mysql.INTEGER(),
               comment='关联数据集ID',
               existing_nullable=True)
    op.alter_column('analysis_smart_tables', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.create_table_comment(
        'course_chapter_progress',
        '章节学习进度表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'course_chapters',
        '课程章节表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'course_courses',
        '课程表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'course_enrollments',
        '课程报名记录表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'exam_answers',
        '答题记录表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'exam_paper_questions',
        '试卷题目表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'exam_papers',
        '试卷表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'exam_question_banks',
        '题库分类表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'exam_questions',
        '考试题目表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'exam_records',
        '考试记录表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('im_contacts', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_contacts', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('im_contacts', 'contact_id',
               existing_type=mysql.INTEGER(),
               comment='联系人ID',
               existing_nullable=False)
    op.alter_column('im_contacts', 'alias',
               existing_type=mysql.VARCHAR(length=50),
               comment='备注名',
               existing_nullable=True)
    op.alter_column('im_contacts', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment='状态',
               existing_nullable=False)
    op.alter_column('im_contacts', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('im_contacts', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_conversation_members', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment='角色',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'unread_count',
               existing_type=mysql.INTEGER(),
               comment='未读数',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'last_read_message_id',
               existing_type=mysql.INTEGER(),
               comment='最后已读消息ID',
               existing_nullable=True)
    op.alter_column('im_conversation_members', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否置顶',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'is_muted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否免打扰',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'joined_at',
               existing_type=mysql.DATETIME(),
               comment='加入时间',
               existing_nullable=False)
    op.alter_column('im_conversations', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_conversations', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment='会话类型',
               existing_nullable=False)
    op.alter_column('im_conversations', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='会话名称',
               existing_nullable=True)
    op.alter_column('im_conversations', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               comment='会话头像',
               existing_nullable=True)
    op.alter_column('im_conversations', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='群主ID',
               existing_nullable=True)
    op.alter_column('im_conversations', 'last_message_id',
               existing_type=mysql.INTEGER(),
               comment='最后消息ID',
               existing_nullable=True)
    op.alter_column('im_conversations', 'last_message_time',
               existing_type=mysql.DATETIME(),
               comment='最后消息时间',
               existing_nullable=True)
    op.alter_column('im_conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('im_conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_message_reads', 'message_id',
               existing_type=mysql.INTEGER(),
               comment='消息ID',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'read_at',
               existing_type=mysql.DATETIME(),
               comment='阅读时间',
               existing_nullable=False)
    op.alter_column('im_messages', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_messages', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('im_messages', 'sender_id',
               existing_type=mysql.INTEGER(),
               comment='发送者ID',
               existing_nullable=False)
    op.alter_column('im_messages', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment='消息类型',
               existing_nullable=False)
    op.alter_column('im_messages', 'content',
               existing_type=mysql.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('im_messages', 'file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='文件路径',
               existing_nullable=True)
    op.alter_column('im_messages', 'file_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='原始文件名',
               existing_nullable=True)
    op.alter_column('im_messages', 'file_size',
               existing_type=mysql.BIGINT(),
               comment='文件大小',
               existing_nullable=True)
    op.alter_column('im_messages', 'file_mime',
               existing_type=mysql.VARCHAR(length=100),
               comment='文件MIME类型',
               existing_nullable=True)
    op.alter_column('im_messages', 'reply_to_id',
               existing_type=mysql.INTEGER(),
               comment='回复消息ID',
               existing_nullable=True)
    op.alter_column('im_messages', 'is_recalled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否撤回',
               existing_nullable=False)
    op.alter_column('im_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='发送时间',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('knowledge_bases', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='知识库名称',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               comment='描述',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'cover',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='封面图',
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='所有者ID',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否公开',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.create_table_comment(
        'knowledge_bases',
        '知识库列表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('knowledge_nodes', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('knowledge_nodes', 'base_id',
               existing_type=mysql.INTEGER(),
               comment='所属知识库ID',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment='父节点ID',
               existing_nullable=True)
    op.alter_column('knowledge_nodes', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='标题',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'node_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='节点类型',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='文档内容',
               existing_nullable=True)
    op.alter_column('knowledge_nodes', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='文件路径',
               existing_nullable=True)
    op.alter_column('knowledge_nodes', 'file_meta',
               existing_type=mysql.JSON(),
               comment='文件元数据',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment='排序',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='状态',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.create_table_comment(
        'knowledge_nodes',
        '知识库节点表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('lens_categories', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='分类名称',
               existing_nullable=False)
    op.alter_column('lens_categories', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               comment='图标',
               existing_nullable=False)
    op.alter_column('lens_categories', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='颜色',
               existing_nullable=True)
    op.alter_column('lens_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序权重',
               existing_nullable=False)
    op.alter_column('lens_categories', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment='父分类ID',
               existing_nullable=True)
    op.alter_column('lens_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_datasources', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='数据源名称',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='数据源类型',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='描述',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'connection_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='数据库连接配置',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'file_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='文件配置',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'api_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='API接口配置',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否激活',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'last_connected_at',
               existing_type=mysql.DATETIME(),
               comment='最后连接时间',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'last_error',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='最后错误信息',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('lens_favorites', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_favorites', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('lens_favorites', 'view_id',
               existing_type=mysql.INTEGER(),
               comment='视图ID',
               existing_nullable=False)
    op.alter_column('lens_favorites', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_recent_views', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_recent_views', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('lens_recent_views', 'view_id',
               existing_type=mysql.INTEGER(),
               comment='视图ID',
               existing_nullable=False)
    op.alter_column('lens_recent_views', 'accessed_at',
               existing_type=mysql.DATETIME(),
               comment='访问时间',
               existing_nullable=False)
    op.alter_column('lens_views', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_views', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='视图名称',
               existing_nullable=False)
    op.alter_column('lens_views', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='描述',
               existing_nullable=True)
    op.alter_column('lens_views', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               comment='图标',
               existing_nullable=False)
    op.alter_column('lens_views', 'category_id',
               existing_type=mysql.INTEGER(),
               comment='所属分类ID',
               existing_nullable=True)
    op.alter_column('lens_views', 'datasource_id',
               existing_type=mysql.INTEGER(),
               comment='关联数据源ID',
               existing_nullable=True)
    op.alter_column('lens_views', 'query_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='查询类型',
               existing_nullable=False)
    op.alter_column('lens_views', 'query_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='查询配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'display_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='显示配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'status_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='状态配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'chart_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='图表配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'required_permission',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='所需权限',
               existing_nullable=True)
    op.alter_column('lens_views', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否公开',
               existing_nullable=False)
    op.alter_column('lens_views', 'view_count',
               existing_type=mysql.INTEGER(),
               comment='访问次数',
               existing_nullable=False)
    op.alter_column('lens_views', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_nullable=False)
    op.alter_column('lens_views', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_views', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('notes_folders', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notes_folders', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='文件夹名称',
               existing_nullable=False)
    op.alter_column('notes_folders', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment='父文件夹ID',
               existing_nullable=True)
    op.alter_column('notes_folders', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('notes_folders', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序权重',
               existing_nullable=False)
    op.alter_column('notes_folders', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('notes_folders', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('notes_note_tags', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notes_note_tags', 'note_id',
               existing_type=mysql.INTEGER(),
               comment='笔记ID',
               existing_nullable=False)
    op.alter_column('notes_note_tags', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment='标签ID',
               existing_nullable=False)
    op.alter_column('notes_notes', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notes_notes', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               comment='标题',
               existing_nullable=False)
    op.alter_column('notes_notes', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='内容',
               existing_nullable=False)
    op.alter_column('notes_notes', 'folder_id',
               existing_type=mysql.INTEGER(),
               comment='所属文件夹ID',
               existing_nullable=True)
    op.alter_column('notes_notes', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('notes_notes', 'is_starred',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否收藏',
               existing_nullable=False)
    op.alter_column('notes_notes', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否置顶',
               existing_nullable=False)
    op.alter_column('notes_notes', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序权重',
               existing_nullable=False)
    op.alter_column('notes_notes', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('notes_notes', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('notes_tags', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notes_tags', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='标签名称',
               existing_nullable=False)
    op.alter_column('notes_tags', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='标签颜色',
               existing_nullable=False)
    op.alter_column('notes_tags', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('notes_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.create_table_comment(
        'video_collections',
        '视频集表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'video_videos',
        '视频表',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'video_videos',
        existing_comment='视频表',
        schema=None
    )
    op.drop_table_comment(
        'video_collections',
        existing_comment='视频集表',
        schema=None
    )
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('notes_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('notes_tags', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('notes_tags', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='标签颜色',
               existing_nullable=False)
    op.alter_column('notes_tags', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='标签名称',
               existing_nullable=False)
    op.alter_column('notes_tags', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notes_notes', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('notes_notes', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('notes_notes', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序权重',
               existing_nullable=False)
    op.alter_column('notes_notes', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否置顶',
               existing_nullable=False)
    op.alter_column('notes_notes', 'is_starred',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否收藏',
               existing_nullable=False)
    op.alter_column('notes_notes', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('notes_notes', 'folder_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属文件夹ID',
               existing_nullable=True)
    op.alter_column('notes_notes', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='内容',
               existing_nullable=False)
    op.alter_column('notes_notes', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               comment=None,
               existing_comment='标题',
               existing_nullable=False)
    op.alter_column('notes_notes', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notes_note_tags', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False)
    op.alter_column('notes_note_tags', 'note_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='笔记ID',
               existing_nullable=False)
    op.alter_column('notes_note_tags', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notes_folders', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('notes_folders', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('notes_folders', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序权重',
               existing_nullable=False)
    op.alter_column('notes_folders', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('notes_folders', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父文件夹ID',
               existing_nullable=True)
    op.alter_column('notes_folders', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='文件夹名称',
               existing_nullable=False)
    op.alter_column('notes_folders', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_views', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('lens_views', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_views', 'created_by',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('lens_views', 'view_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='访问次数',
               existing_nullable=False)
    op.alter_column('lens_views', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否公开',
               existing_nullable=False)
    op.alter_column('lens_views', 'required_permission',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='所需权限',
               existing_nullable=True)
    op.alter_column('lens_views', 'chart_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='图表配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'status_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='状态配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'display_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='显示配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'query_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='查询配置',
               existing_nullable=True)
    op.alter_column('lens_views', 'query_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='查询类型',
               existing_nullable=False)
    op.alter_column('lens_views', 'datasource_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联数据源ID',
               existing_nullable=True)
    op.alter_column('lens_views', 'category_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属分类ID',
               existing_nullable=True)
    op.alter_column('lens_views', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               comment=None,
               existing_comment='图标',
               existing_nullable=False)
    op.alter_column('lens_views', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('lens_views', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='视图名称',
               existing_nullable=False)
    op.alter_column('lens_views', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_recent_views', 'accessed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='访问时间',
               existing_nullable=False)
    op.alter_column('lens_recent_views', 'view_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='视图ID',
               existing_nullable=False)
    op.alter_column('lens_recent_views', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('lens_recent_views', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_favorites', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_favorites', 'view_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='视图ID',
               existing_nullable=False)
    op.alter_column('lens_favorites', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('lens_favorites', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_datasources', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'created_by',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'last_error',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='最后错误信息',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'last_connected_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后连接时间',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'api_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='API接口配置',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'file_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='文件配置',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'connection_config',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='数据库连接配置',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('lens_datasources', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='数据源类型',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='数据源名称',
               existing_nullable=False)
    op.alter_column('lens_datasources', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lens_categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('lens_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('lens_categories', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父分类ID',
               existing_nullable=True)
    op.alter_column('lens_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序权重',
               existing_nullable=False)
    op.alter_column('lens_categories', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='颜色',
               existing_nullable=True)
    op.alter_column('lens_categories', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               comment=None,
               existing_comment='图标',
               existing_nullable=False)
    op.alter_column('lens_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=False)
    op.alter_column('lens_categories', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'knowledge_nodes',
        existing_comment='知识库节点表',
        schema=None
    )
    op.alter_column('knowledge_nodes', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'created_by',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'file_meta',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='文件元数据',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='文件路径',
               existing_nullable=True)
    op.alter_column('knowledge_nodes', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='文档内容',
               existing_nullable=True)
    op.alter_column('knowledge_nodes', 'node_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='节点类型',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='标题',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父节点ID',
               existing_nullable=True)
    op.alter_column('knowledge_nodes', 'base_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属知识库ID',
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'knowledge_bases',
        existing_comment='知识库列表',
        schema=None
    )
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否公开',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所有者ID',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'cover',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='封面图',
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               comment=None,
               existing_comment='描述',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='知识库名称',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='发送时间',
               existing_nullable=False)
    op.alter_column('im_messages', 'is_recalled',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否撤回',
               existing_nullable=False)
    op.alter_column('im_messages', 'reply_to_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='回复消息ID',
               existing_nullable=True)
    op.alter_column('im_messages', 'file_mime',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='文件MIME类型',
               existing_nullable=True)
    op.alter_column('im_messages', 'file_size',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='文件大小',
               existing_nullable=True)
    op.alter_column('im_messages', 'file_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='原始文件名',
               existing_nullable=True)
    op.alter_column('im_messages', 'file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='文件路径',
               existing_nullable=True)
    op.alter_column('im_messages', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('im_messages', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='消息类型',
               existing_nullable=False)
    op.alter_column('im_messages', 'sender_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='发送者ID',
               existing_nullable=False)
    op.alter_column('im_messages', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.alter_column('im_messages', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_message_reads', 'read_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='阅读时间',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'message_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='消息ID',
               existing_nullable=False)
    op.alter_column('im_message_reads', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('im_conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('im_conversations', 'last_message_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后消息时间',
               existing_nullable=True)
    op.alter_column('im_conversations', 'last_message_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='最后消息ID',
               existing_nullable=True)
    op.alter_column('im_conversations', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='群主ID',
               existing_nullable=True)
    op.alter_column('im_conversations', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='会话头像',
               existing_nullable=True)
    op.alter_column('im_conversations', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='会话名称',
               existing_nullable=True)
    op.alter_column('im_conversations', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='会话类型',
               existing_nullable=False)
    op.alter_column('im_conversations', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_conversation_members', 'joined_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='加入时间',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'is_muted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否免打扰',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'is_pinned',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否置顶',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'last_read_message_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='最后已读消息ID',
               existing_nullable=True)
    op.alter_column('im_conversation_members', 'unread_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='未读数',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='角色',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.alter_column('im_conversation_members', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('im_contacts', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('im_contacts', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('im_contacts', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('im_contacts', 'alias',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='备注名',
               existing_nullable=True)
    op.alter_column('im_contacts', 'contact_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='联系人ID',
               existing_nullable=False)
    op.alter_column('im_contacts', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('im_contacts', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'exam_records',
        existing_comment='考试记录表',
        schema=None
    )
    op.drop_table_comment(
        'exam_questions',
        existing_comment='考试题目表',
        schema=None
    )
    op.drop_table_comment(
        'exam_question_banks',
        existing_comment='题库分类表',
        schema=None
    )
    op.drop_table_comment(
        'exam_papers',
        existing_comment='试卷表',
        schema=None
    )
    op.drop_table_comment(
        'exam_paper_questions',
        existing_comment='试卷题目表',
        schema=None
    )
    op.drop_table_comment(
        'exam_answers',
        existing_comment='答题记录表',
        schema=None
    )
    op.drop_table_comment(
        'course_enrollments',
        existing_comment='课程报名记录表',
        schema=None
    )
    op.drop_table_comment(
        'course_courses',
        existing_comment='课程表',
        schema=None
    )
    op.drop_table_comment(
        'course_chapters',
        existing_comment='课程章节表',
        schema=None
    )
    op.drop_table_comment(
        'course_chapter_progress',
        existing_comment='章节学习进度表',
        schema=None
    )
    op.alter_column('analysis_smart_tables', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'dataset_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联数据集ID',
               existing_nullable=True)
    op.alter_column('analysis_smart_tables', 'config',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='表格配置',
               existing_nullable=True)
    op.alter_column('analysis_smart_tables', 'fields',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='字段定义',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='表格名称',
               existing_nullable=False)
    op.alter_column('analysis_smart_tables', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_smart_table_data', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'row_data',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='行数据',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'table_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='智能表格ID',
               existing_nullable=False)
    op.alter_column('analysis_smart_table_data', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_smart_reports', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_reports', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_reports', 'data_row',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='数据行模式',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'dataset_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联数据集ID',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'template_vars',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='模板变量',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'content_md',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Markdown内容',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'content_html',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='HTML内容',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'template_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='Word模板路径',
               existing_nullable=True)
    op.alter_column('analysis_smart_reports', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='模板名称',
               existing_nullable=False)
    op.alter_column('analysis_smart_reports', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_smart_report_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               comment=None,
               existing_comment='报告全文',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'pdf_file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='PDF文件路径',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'docx_file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='Word文件路径',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='记录名称',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'report_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='报告模板ID',
               existing_nullable=False)
    op.alter_column('analysis_smart_report_records', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_models', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_models', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_models', 'status',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('analysis_models', 'graph_config',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='流程图配置',
               existing_nullable=True)
    op.alter_column('analysis_models', 'description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='模型描述',
               existing_nullable=True)
    op.alter_column('analysis_models', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='模型名称',
               existing_nullable=False)
    op.alter_column('analysis_models', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_datasets', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'row_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='数据行数',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'config',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='导入配置',
               existing_nullable=True)
    op.alter_column('analysis_datasets', 'table_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='DuckDB表名',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'source_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='来源类型',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='数据集名称',
               existing_nullable=False)
    op.alter_column('analysis_datasets', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_dashboards', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_dashboards', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_dashboards', 'widgets',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='组件配置',
               existing_nullable=True)
    op.alter_column('analysis_dashboards', 'description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='仪表盘描述',
               existing_nullable=True)
    op.alter_column('analysis_dashboards', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='仪表盘名称',
               existing_nullable=False)
    op.alter_column('analysis_dashboards', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('analysis_charts', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='图表描述',
               existing_nullable=True)
    op.alter_column('analysis_charts', 'config',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='图表配置',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'chart_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='图表类型',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'dataset_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联数据集ID',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='图表名称',
               existing_nullable=False)
    op.alter_column('analysis_charts', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'album_photos',
        existing_comment='照片表',
        schema=None
    )
    op.drop_table_comment(
        'album_albums',
        existing_comment='相册表',
        schema=None
    )
    # ### end Alembic commands ###







