"""complete missing comments and fix typos

Revision ID: 6b2c4352d4fd
Revises: 68d1ecd89ecd
Create Date: 2026-01-03 17:18:23.631350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b2c4352d4fd'
down_revision: Union[str, None] = '68d1ecd89ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_comment='报告全文',
               existing_nullable=True)
    op.create_table_comment(
        'lens_categories',
        '数据视图分类表',
        existing_comment='DataLens 视图分类表',
        schema=None
    )
    op.create_table_comment(
        'lens_datasources',
        '外部数据源配置表',
        existing_comment='DataLens 外部数据源配置表',
        schema=None
    )
    op.create_table_comment(
        'lens_favorites',
        '数据视图收藏表',
        existing_comment='DataLens 用户收藏表',
        schema=None
    )
    op.create_table_comment(
        'lens_recent_views',
        '最近访问记录表',
        existing_comment='DataLens 最近访问记录表',
        schema=None
    )
    op.create_table_comment(
        'lens_views',
        '数据视图配置表',
        existing_comment='DataLens 数据视图配置表',
        schema=None
    )
    op.alter_column('schedule_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'schedule_categories',
        '日程分类表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('schedule_events', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('schedule_events', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.create_table_comment(
        'schedule_events',
        '日程事件表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'schedule_reminders',
        '日程提醒表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('sys_announcements', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_announcements', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment='公告标题',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'content',
               existing_type=mysql.TEXT(),
               comment='公告内容',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment='类型',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'author_id',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否发布',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'is_top',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否置顶',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'start_at',
               existing_type=mysql.DATETIME(),
               comment='开始时间',
               existing_nullable=True)
    op.alter_column('sys_announcements', 'end_at',
               existing_type=mysql.DATETIME(),
               comment='结束时间',
               existing_nullable=True)
    op.alter_column('sys_announcements', 'views',
               existing_type=mysql.INTEGER(),
               comment='浏览次数',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_backups', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_backups', 'backup_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='备份类型',
               existing_nullable=False)
    op.alter_column('sys_backups', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment='备份状态',
               existing_nullable=False)
    op.alter_column('sys_backups', 'file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='备份文件路径',
               existing_nullable=True)
    op.alter_column('sys_backups', 'file_size',
               existing_type=mysql.INTEGER(),
               comment='备份文件大小(字节)',
               existing_nullable=True)
    op.alter_column('sys_backups', 'description',
               existing_type=mysql.TEXT(),
               comment='备份描述',
               existing_nullable=True)
    op.alter_column('sys_backups', 'error_message',
               existing_type=mysql.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('sys_backups', 'created_by',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_nullable=True)
    op.alter_column('sys_backups', 'started_at',
               existing_type=mysql.DATETIME(),
               comment='开始时间',
               existing_nullable=True)
    op.alter_column('sys_backups', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('sys_backups', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_files', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_files', 'filename',
               existing_type=mysql.VARCHAR(length=255),
               comment='原始文件名',
               existing_nullable=False)
    op.alter_column('sys_files', 'storage_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='存储路径',
               existing_nullable=False)
    op.alter_column('sys_files', 'file_size',
               existing_type=mysql.INTEGER(),
               comment='文件大小(字节)',
               existing_nullable=False)
    op.alter_column('sys_files', 'mime_type',
               existing_type=mysql.VARCHAR(length=100),
               comment='MIME类型',
               existing_nullable=True)
    op.alter_column('sys_files', 'uploader_id',
               existing_type=mysql.INTEGER(),
               comment='上传者ID',
               existing_nullable=True)
    op.alter_column('sys_files', 'category',
               existing_type=mysql.VARCHAR(length=50),
               comment='业务分类',
               existing_nullable=False,
               existing_server_default=sa.text("'attachment'"))
    op.alter_column('sys_files', 'ref_id',
               existing_type=mysql.INTEGER(),
               comment='关联业务ID',
               existing_nullable=True)
    op.alter_column('sys_files', 'description',
               existing_type=mysql.TEXT(),
               comment='文件描述',
               existing_nullable=True)
    op.alter_column('sys_files', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_logs', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_logs', 'level',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='日志级别',
               existing_nullable=False)
    op.alter_column('sys_logs', 'module',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='模块名称',
               existing_nullable=False)
    op.alter_column('sys_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='操作类型',
               existing_nullable=False)
    op.alter_column('sys_logs', 'message',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='日志内容',
               existing_nullable=True)
    op.alter_column('sys_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='操作用户ID',
               existing_nullable=True)
    op.alter_column('sys_logs', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='IP地址',
               existing_nullable=True)
    op.alter_column('sys_logs', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='用户代理',
               existing_nullable=True)
    op.alter_column('sys_logs', 'request_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               comment='请求方法',
               existing_nullable=True)
    op.alter_column('sys_logs', 'request_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='请求路径',
               existing_nullable=True)
    op.alter_column('sys_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_metrics', 'metric_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='指标类型',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'metric_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='指标名称',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'value',
               existing_type=mysql.FLOAT(),
               comment='指标值',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'unit',
               existing_type=mysql.VARCHAR(length=20),
               comment='单位',
               existing_nullable=True)
    op.alter_column('sys_metrics', 'extra_metadata',
               existing_type=mysql.JSON(),
               comment='额外元数据',
               existing_nullable=True)
    op.alter_column('sys_metrics', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_module_configs', 'module_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='模块ID',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'config',
               existing_type=mysql.JSON(),
               comment='配置内容',
               existing_nullable=True)
    op.alter_column('sys_module_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_notifications', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='接收用户ID',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'sender_id',
               existing_type=mysql.INTEGER(),
               comment='发送者ID',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment='通知标题',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'content',
               existing_type=mysql.TEXT(),
               comment='通知内容',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment='通知类型',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否已读',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'read_at',
               existing_type=mysql.DATETIME(),
               comment='阅读时间',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'action_url',
               existing_type=mysql.VARCHAR(length=500),
               comment='操作链接',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_settings', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_settings', 'key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='配置键',
               existing_nullable=False)
    op.alter_column('sys_settings', 'value',
               existing_type=mysql.JSON(),
               comment='配置值',
               existing_nullable=True)
    op.alter_column('sys_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_user_groups', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_user_groups', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment='组名称',
               existing_nullable=False)
    op.alter_column('sys_user_groups', 'permissions',
               existing_type=mysql.JSON(),
               comment='权限列表',
               existing_nullable=True)
    op.alter_column('sys_user_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_user_groups', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_users', 'id',
               existing_type=mysql.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('sys_users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               comment='手机号码',
               existing_nullable=True)
    op.alter_column('sys_users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='密码哈希',
               existing_nullable=False)
    op.alter_column('sys_users', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='昵称',
               existing_nullable=True)
    op.alter_column('sys_users', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('sys_users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='角色',
               existing_nullable=False)
    op.alter_column('sys_users', 'permissions',
               existing_type=mysql.JSON(),
               comment='权限列表',
               existing_nullable=True)
    op.alter_column('sys_users', 'role_ids',
               existing_type=mysql.JSON(),
               comment='角色ID列表',
               existing_nullable=True)
    op.alter_column('sys_users', 'settings',
               existing_type=mysql.JSON(),
               comment='个性化设置',
               existing_nullable=True)
    op.alter_column('sys_users', 'storage_quota',
               existing_type=mysql.INTEGER(),
               comment='存储配额(字节)',
               existing_nullable=True)
    op.alter_column('sys_users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否激活',
               existing_nullable=False)
    op.alter_column('sys_users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('sys_users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('sys_users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('sys_users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False)
    op.alter_column('sys_users', 'storage_quota',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='存储配额(字节)',
               existing_nullable=True)
    op.alter_column('sys_users', 'settings',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='个性化设置',
               existing_nullable=True)
    op.alter_column('sys_users', 'role_ids',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='角色ID列表',
               existing_nullable=True)
    op.alter_column('sys_users', 'permissions',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='权限列表',
               existing_nullable=True)
    op.alter_column('sys_users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='角色',
               existing_nullable=False)
    op.alter_column('sys_users', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('sys_users', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='昵称',
               existing_nullable=True)
    op.alter_column('sys_users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
    op.alter_column('sys_users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               comment=None,
               existing_comment='手机号码',
               existing_nullable=True)
    op.alter_column('sys_users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('sys_users', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_user_groups', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_user_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_user_groups', 'permissions',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='权限列表',
               existing_nullable=True)
    op.alter_column('sys_user_groups', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='组名称',
               existing_nullable=False)
    op.alter_column('sys_user_groups', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_settings', 'value',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='配置值',
               existing_nullable=True)
    op.alter_column('sys_settings', 'key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='配置键',
               existing_nullable=False)
    op.alter_column('sys_settings', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'action_url',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='操作链接',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'read_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='阅读时间',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否已读',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='通知类型',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='通知内容',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='通知标题',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'sender_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='发送者ID',
               existing_nullable=True)
    op.alter_column('sys_notifications', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='接收用户ID',
               existing_nullable=False)
    op.alter_column('sys_notifications', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_module_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'config',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='配置内容',
               existing_nullable=True)
    op.alter_column('sys_module_configs', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'module_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='模块ID',
               existing_nullable=False)
    op.alter_column('sys_module_configs', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_metrics', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'extra_metadata',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='额外元数据',
               existing_nullable=True)
    op.alter_column('sys_metrics', 'unit',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='单位',
               existing_nullable=True)
    op.alter_column('sys_metrics', 'value',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='指标值',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'metric_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='指标名称',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'metric_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='指标类型',
               existing_nullable=False)
    op.alter_column('sys_metrics', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_logs', 'request_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment=None,
               existing_comment='请求路径',
               existing_nullable=True)
    op.alter_column('sys_logs', 'request_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               comment=None,
               existing_comment='请求方法',
               existing_nullable=True)
    op.alter_column('sys_logs', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment=None,
               existing_comment='用户代理',
               existing_nullable=True)
    op.alter_column('sys_logs', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='IP地址',
               existing_nullable=True)
    op.alter_column('sys_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='操作用户ID',
               existing_nullable=True)
    op.alter_column('sys_logs', 'message',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='日志内容',
               existing_nullable=True)
    op.alter_column('sys_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               comment=None,
               existing_comment='操作类型',
               existing_nullable=False)
    op.alter_column('sys_logs', 'module',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='模块名称',
               existing_nullable=False)
    op.alter_column('sys_logs', 'level',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='日志级别',
               existing_nullable=False)
    op.alter_column('sys_logs', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_files', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_files', 'description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='文件描述',
               existing_nullable=True)
    op.alter_column('sys_files', 'ref_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联业务ID',
               existing_nullable=True)
    op.alter_column('sys_files', 'category',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='业务分类',
               existing_nullable=False,
               existing_server_default=sa.text("'attachment'"))
    op.alter_column('sys_files', 'uploader_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='上传者ID',
               existing_nullable=True)
    op.alter_column('sys_files', 'mime_type',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='MIME类型',
               existing_nullable=True)
    op.alter_column('sys_files', 'file_size',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文件大小(字节)',
               existing_nullable=False)
    op.alter_column('sys_files', 'storage_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='存储路径',
               existing_nullable=False)
    op.alter_column('sys_files', 'filename',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='原始文件名',
               existing_nullable=False)
    op.alter_column('sys_files', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_backups', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_backups', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('sys_backups', 'started_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('sys_backups', 'created_by',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=True)
    op.alter_column('sys_backups', 'error_message',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('sys_backups', 'description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='备份描述',
               existing_nullable=True)
    op.alter_column('sys_backups', 'file_size',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='备份文件大小(字节)',
               existing_nullable=True)
    op.alter_column('sys_backups', 'file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='备份文件路径',
               existing_nullable=True)
    op.alter_column('sys_backups', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='备份状态',
               existing_nullable=False)
    op.alter_column('sys_backups', 'backup_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='备份类型',
               existing_nullable=False)
    op.alter_column('sys_backups', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_announcements', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'views',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='浏览次数',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'end_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=True)
    op.alter_column('sys_announcements', 'start_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('sys_announcements', 'is_top',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否置顶',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'is_published',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否发布',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'author_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='类型',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='公告内容',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='公告标题',
               existing_nullable=False)
    op.alter_column('sys_announcements', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'schedule_reminders',
        existing_comment='日程提醒表',
        schema=None
    )
    op.drop_table_comment(
        'schedule_events',
        existing_comment='日程事件表',
        schema=None
    )
    op.alter_column('schedule_events', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('schedule_events', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_table_comment(
        'schedule_categories',
        existing_comment='日程分类表',
        schema=None
    )
    op.alter_column('schedule_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'lens_views',
        'DataLens 数据视图配置表',
        existing_comment='数据视图配置表',
        schema=None
    )
    op.create_table_comment(
        'lens_recent_views',
        'DataLens 最近访问记录表',
        existing_comment='最近访问记录表',
        schema=None
    )
    op.create_table_comment(
        'lens_favorites',
        'DataLens 用户收藏表',
        existing_comment='数据视图收藏表',
        schema=None
    )
    op.create_table_comment(
        'lens_datasources',
        'DataLens 外部数据源配置表',
        existing_comment='外部数据源配置表',
        schema=None
    )
    op.create_table_comment(
        'lens_categories',
        'DataLens 视图分类表',
        existing_comment='数据视图分类表',
        schema=None
    )
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_comment='报告全文',
               existing_nullable=True)
    # ### end Alembic commands ###







