"""initial_schema_v2_4_2

Revision ID: 85839bcca7af
Revises: 
Create Date: 2026-01-17 21:46:26.544003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85839bcca7af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_module', 'sys_user_modules', ['user_id', 'module_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_module', 'sys_user_modules', type_='unique')
    # ### end Alembic commands ###







