"""add_vault_recovery_key_fields

Revision ID: 94efdfacd5d0
Revises: 4e3138b5bab4
Create Date: 2026-01-17 17:11:40.225552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94efdfacd5d0'
down_revision: Union[str, None] = '4e3138b5bab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_master_keys', sa.Column('recovery_salt', sa.String(length=64), nullable=True, comment='恢复码盐值'))
    op.add_column('vault_master_keys', sa.Column('encrypted_data_key', sa.Text(), nullable=True, comment='用恢复码加密的数据密钥'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_master_keys', 'encrypted_data_key')
    op.drop_column('vault_master_keys', 'recovery_salt')
    # ### end Alembic commands ###







