"""add_vault_lock_fields

Revision ID: a66001197bfa
Revises: 94efdfacd5d0
Create Date: 2026-01-17 17:42:57.220698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66001197bfa'
down_revision: Union[str, None] = '94efdfacd5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_master_keys', sa.Column('failed_attempts', sa.Integer(), nullable=False, comment='连续失败尝试次数'))
    op.add_column('vault_master_keys', sa.Column('is_locked', sa.Boolean(), nullable=False, comment='是否已锁定'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_master_keys', 'is_locked')
    op.drop_column('vault_master_keys', 'failed_attempts')
    # ### end Alembic commands ###







