"""add exam module tables

Revision ID: ab8e62e3261c
Revises: 0b78536eb0ca
Create Date: 2026-01-03 16:35:36.638865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab8e62e3261c'
down_revision: Union[str, None] = '0b78536eb0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='试卷标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='试卷描述'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='总分'),
    sa.Column('pass_score', sa.Float(), nullable=True, comment='及格分数'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='考试时长(分钟)'),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True, comment='题目乱序'),
    sa.Column('shuffle_options', sa.Boolean(), nullable=True, comment='选项乱序'),
    sa.Column('show_answer', sa.Boolean(), nullable=True, comment='交卷后显示答案'),
    sa.Column('allow_review', sa.Boolean(), nullable=True, comment='允许查看解析'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='考试开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='考试结束时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='试卷状态'),
    sa.Column('question_count', sa.Integer(), nullable=True, comment='题目数量'),
    sa.Column('take_count', sa.Integer(), nullable=True, comment='参考人数'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_user_id'), 'exam_papers', ['user_id'], unique=False)
    op.create_table('exam_question_banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='题库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='题库描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('question_count', sa.Integer(), nullable=True, comment='题目数量'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_question_banks_user_id'), 'exam_question_banks', ['user_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('bank_id', sa.Integer(), nullable=True, comment='所属题库ID'),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment='题目类型'),
    sa.Column('title', sa.Text(), nullable=False, comment='题干'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项列表(JSON)'),
    sa.Column('answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('analysis', sa.Text(), nullable=True, comment='答案解析'),
    sa.Column('score', sa.Float(), nullable=True, comment='分值'),
    sa.Column('difficulty', sa.Integer(), nullable=True, comment='难度等级(1-5)'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签(逗号分隔)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['bank_id'], ['exam_question_banks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_questions_bank_id'), 'exam_questions', ['bank_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_user_id'), 'exam_questions', ['user_id'], unique=False)
    op.create_table('exam_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='考生ID'),
    sa.Column('paper_id', sa.Integer(), nullable=False, comment='试卷ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='考试状态'),
    sa.Column('score', sa.Float(), nullable=True, comment='得分'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='总分'),
    sa.Column('is_passed', sa.Boolean(), nullable=True, comment='是否及格'),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='正确数量'),
    sa.Column('wrong_count', sa.Integer(), nullable=True, comment='错误数量'),
    sa.Column('unanswered_count', sa.Integer(), nullable=True, comment='未答数量'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('submit_time', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('used_seconds', sa.Integer(), nullable=True, comment='用时(秒)'),
    sa.Column('grader_id', sa.Integer(), nullable=True, comment='阅卷人ID'),
    sa.Column('graded_at', sa.DateTime(), nullable=True, comment='阅卷时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='阅卷评语'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_records_paper_id'), 'exam_records', ['paper_id'], unique=False)
    op.create_index(op.f('ix_exam_records_user_id'), 'exam_records', ['user_id'], unique=False)
    op.create_table('exam_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='考试记录ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('user_answer', sa.Text(), nullable=True, comment='用户答案'),
    sa.Column('correct_answer', sa.Text(), nullable=True, comment='正确答案'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确'),
    sa.Column('score', sa.Float(), nullable=True, comment='得分'),
    sa.Column('max_score', sa.Float(), nullable=True, comment='满分'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评语'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['record_id'], ['exam_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_answers_question_id'), 'exam_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_answers_record_id'), 'exam_answers', ['record_id'], unique=False)
    op.create_table('exam_paper_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('paper_id', sa.Integer(), nullable=False, comment='试卷ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('score', sa.Float(), nullable=True, comment='本题分值(可覆盖题目默认分值)'),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_paper_questions_paper_id'), 'exam_paper_questions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_exam_paper_questions_question_id'), 'exam_paper_questions', ['question_id'], unique=False)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('analysis_smart_report_records', 'full_content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_exam_paper_questions_question_id'), table_name='exam_paper_questions')
    op.drop_index(op.f('ix_exam_paper_questions_paper_id'), table_name='exam_paper_questions')
    op.drop_table('exam_paper_questions')
    op.drop_index(op.f('ix_exam_answers_record_id'), table_name='exam_answers')
    op.drop_index(op.f('ix_exam_answers_question_id'), table_name='exam_answers')
    op.drop_table('exam_answers')
    op.drop_index(op.f('ix_exam_records_user_id'), table_name='exam_records')
    op.drop_index(op.f('ix_exam_records_paper_id'), table_name='exam_records')
    op.drop_table('exam_records')
    op.drop_index(op.f('ix_exam_questions_user_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_bank_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_exam_question_banks_user_id'), table_name='exam_question_banks')
    op.drop_table('exam_question_banks')
    op.drop_index(op.f('ix_exam_papers_user_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    # ### end Alembic commands ###







