"""remove_smart_report_tables

Revision ID: af6011a6de52
Revises: 0b4212b0fda5
Create Date: 2026-01-14 21:47:52.578775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af6011a6de52'
down_revision: Union[str, None] = '0b4212b0fda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_smart_report_records')
    op.drop_table('analysis_smart_reports')
    op.alter_column('blog_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('blog_posts', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('blog_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('course_chapter_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('course_chapters', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('course_chapters', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('course_courses', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('course_courses', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('map_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='最后更新时间',
               existing_nullable=True)
    op.alter_column('map_markers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('map_tile_sources', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='入库时间',
               existing_nullable=True)
    op.alter_column('map_trails', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('map_trails', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('transfer_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('transfer_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('map_trails', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('map_trails', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('map_tile_sources', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='入库时间',
               existing_nullable=True)
    op.alter_column('map_markers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('map_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='最后更新时间',
               existing_nullable=True)
    op.alter_column('course_courses', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('course_courses', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('course_chapters', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('course_chapters', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('course_chapter_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('blog_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('blog_posts', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('blog_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_table('analysis_smart_reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='模板名称'),
    sa.Column('template_path', mysql.VARCHAR(length=500), nullable=True, comment='Word模板路径'),
    sa.Column('content_html', mysql.TEXT(), nullable=True, comment='HTML内容'),
    sa.Column('content_md', mysql.TEXT(), nullable=True, comment='Markdown内容'),
    sa.Column('template_vars', mysql.JSON(), nullable=True, comment='模板变量'),
    sa.Column('dataset_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='关联数据集ID'),
    sa.Column('data_row', mysql.VARCHAR(length=50), nullable=True, comment='数据行模式'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能报告模版表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='智能报告模版表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analysis_smart_report_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='报告模板ID'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='记录名称'),
    sa.Column('docx_file_path', mysql.VARCHAR(length=500), nullable=False, comment='Word文件路径'),
    sa.Column('pdf_file_path', mysql.VARCHAR(length=500), nullable=True, comment='PDF文件路径'),
    sa.Column('full_content', mysql.LONGTEXT(), nullable=True, comment='报告全文'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能报告生成记录表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='智能报告生成记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###







