"""Add product table

Revision ID: e129b55f941a
Revises: 
Create Date: 2025-12-10 13:30:44.827922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e129b55f941a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_manager_items_user_id', table_name='task_manager_items')
    op.drop_table('task_manager_items')
    op.drop_index('ix_sys_modules_module_id', table_name='sys_modules')
    op.drop_table('sys_modules')
    op.drop_index('ix_sys_roles_name', table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_index('ix_announcement_announcements_author_id', table_name='announcement_announcements')
    op.drop_table('announcement_announcements')
    op.add_column('product_items', sa.Column('content', sa.Text(), nullable=True, comment='内容'))
    op.alter_column('product_items', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='标题',
               existing_comment='商品名称',
               existing_nullable=False)
    op.alter_column('product_items', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_comment='是否上架',
               existing_nullable=True)
    op.drop_column('product_items', 'description')
    op.drop_column('product_items', 'stock')
    op.drop_column('product_items', 'price')
    op.drop_column('product_items', 'category')
    op.add_column('sys_module_configs', sa.Column('module_id', sa.String(length=50), nullable=False))
    op.add_column('sys_module_configs', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.drop_index('ix_sys_module_configs_module_name', table_name='sys_module_configs')
    op.create_index(op.f('ix_sys_module_configs_module_id'), 'sys_module_configs', ['module_id'], unique=True)
    op.drop_column('sys_module_configs', 'display_name')
    op.drop_column('sys_module_configs', 'sort_order')
    op.drop_column('sys_module_configs', 'icon')
    op.drop_column('sys_module_configs', 'module_name')
    op.drop_column('sys_module_configs', 'is_enabled')
    op.alter_column('sys_settings', 'value',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_column('sys_user_groups', 'description')
    op.drop_column('sys_user_groups', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user_groups', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('sys_user_groups', sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
    op.alter_column('sys_settings', 'value',
               existing_type=mysql.JSON(),
               nullable=False)
    op.add_column('sys_module_configs', sa.Column('is_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('sys_module_configs', sa.Column('module_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('sys_module_configs', sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('sys_module_configs', sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_module_configs', sa.Column('display_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_index(op.f('ix_sys_module_configs_module_id'), table_name='sys_module_configs')
    op.create_index('ix_sys_module_configs_module_name', 'sys_module_configs', ['module_name'], unique=True)
    op.drop_column('sys_module_configs', 'enabled')
    op.drop_column('sys_module_configs', 'module_id')
    op.add_column('product_items', sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='商品分类'))
    op.add_column('product_items', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='商品价格'))
    op.add_column('product_items', sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False, comment='库存数量'))
    op.add_column('product_items', sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='商品描述'))
    op.alter_column('product_items', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否上架',
               existing_comment='是否启用',
               existing_nullable=True)
    op.alter_column('product_items', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='商品名称',
               existing_comment='标题',
               existing_nullable=False)
    op.drop_column('product_items', 'content')
    op.create_table('announcement_announcements',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_top', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('start_at', mysql.DATETIME(), nullable=True),
    sa.Column('end_at', mysql.DATETIME(), nullable=True),
    sa.Column('views', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_announcement_announcements_author_id', 'announcement_announcements', ['author_id'], unique=False)
    op.create_table('sys_roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('permissions', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sys_roles_name', 'sys_roles', ['name'], unique=True)
    op.create_table('sys_modules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('config', mysql.JSON(), nullable=True),
    sa.Column('installed_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sys_modules_module_id', 'sys_modules', ['module_id'], unique=True)
    op.create_table('task_manager_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='所属用户ID'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='内容'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否启用'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_task_manager_items_user_id', 'task_manager_items', ['user_id'], unique=False)
    # ### end Alembic commands ###

